apiVersion: v1
kind: Service
metadata:
  name: midnight1hour-service
spec:
  selector:
    app: midnight1hour
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer

